name: Release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ 'master' ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release Dry-Run
        if: github.ref != 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CI: true
        run: npx semantic-release --dry-run --branches ${GITHUB_REF#refs/heads/}
      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CI: true
        run: npx semantic-release
